'on': pull_request

name: MyTowerDefenceVR Pipeline

jobs:

  build:
    runs-on: [self-hosted,macOS]

    env:
      UNITY_VERSION: 2020.2.0f1

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
        clean: false
        fetch-depth: 0
        
    
    - name: Unity Edit Test
      run: |
        /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity -quit -batchmode -nographics -logFile \
          -projectPath ./ -testPlatform editmode -runTests -debugCodeOptimization -enableCodeCoverage

    - name: Unity Play Test
      run: |
        /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity -quit -batchmode -nographics -logFile \
          -projectPath ./ -testPlatform playmode -runTests -debugCodeOptimization -enableCodeCoverage

    - name: Unity Coverage
      run: |
        /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity -quit -batchmode -nographics -logFile \
          -projectPath ./ -debugCodeOptimization -enableCodeCoverage -coverageOptions generateHtmlReport;generateBadgeReport